# Generated by Django 2.1.5 on 2019-02-10 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='birthCerts/%Y/%m')),
                ('id_scan', models.FileField(blank=True, null=True, upload_to='ids/%Y/%m')),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_tel_number', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_school', models.CharField(blank=True, max_length=100, null=True)),
                ('PLE_Certificate', models.FileField(blank=True, null=True, upload_to='PLE-certs/%Y/%m')),
                ('olevel_school', models.CharField(blank=True, max_length=100, null=True)),
                ('olevel_Certificate', models.FileField(blank=True, null=True, upload_to='olevel-certs/%Y/%m')),
                ('alevel_school', models.CharField(blank=True, max_length=100, null=True)),
                ('aggregates', models.IntegerField()),
                ('alevel_Certificate', models.FileField(blank=True, null=True, upload_to='alevel-certs/%Y/%m')),
                ('first_course', models.CharField(choices=[('BEduc', 'BEduc'), ('LAW', 'LAW'), ('BSTAT', 'BSTAT')], max_length=100)),
                ('given_first', models.BooleanField(default=False)),
                ('second_course', models.CharField(choices=[('BEduc', 'BEduc'), ('LAW', 'LAW'), ('BSTAT', 'BSTAT')], max_length=100)),
                ('given_second', models.BooleanField(default=False)),
                ('third_course', models.CharField(choices=[('BEduc', 'BEduc'), ('LAW', 'LAW'), ('BSTAT', 'BSTAT')], max_length=100)),
                ('given_third', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
