# Generated by Django 2.1.5 on 2019-02-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aggregates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
