# Generated by Django 2.1.5 on 2019-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190210_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='given_first',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='given_second',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='given_third',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='third_course',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text='eg. First Last', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, help_text='0700000000', null=True),
        ),
    ]
