# Generated by Django 2.1.5 on 2019-03-23 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190323_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='eg. 2019', max_length=122)),
                ('course_being_applied_for', models.CharField(help_text='BBA, PGDE, etc', max_length=122)),
                ('campus', models.CharField(choices=[('Main campus', 'Main campus'), ('Kampala campus', 'Kampala campus')], max_length=122)),
                ('programme', models.CharField(choices=[('Weekend', 'Weekend'), ('Evening', 'Evening'), ('Inservice', 'Inservice')], max_length=122)),
                ('resident', models.BooleanField(default=False, help_text='All fresh stuents of the Main Campus MUST stay in the university halls')),
                ('given', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
