# Generated by Django 2.1.5 on 2019-03-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='given',
            new_name='qualifies',
        ),
    ]
