# Generated by Django 2.1.5 on 2019-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190323_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='time_stamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
